const prefix = 'CONNECTION_CONFIGs__';

export const TOGGLE_MENU_ITEM = 'APP_MENU__TOGGLE_MENU_ITEM';
export const MENU_ITEM_SOURCES = 'APP_MENU__ITEM_SOURCES';
export const MENU_ITEM_DISPLAYS = 'APP_MENU__ITEM_DISPLAYS';
export const MENU_ITEM_WALLS = 'APP_MENU__ITEM_WALLS';
export const MENU_ITEM_ZONES = 'APP_MENU__ITEM_ZONES';
export const MENU_ITEM_SERVER = 'APP_MENU__ITEM_SERVER';
export const MENU_ITEM_HELP = 'APP_MENU__ITEM_HELP';
