export const SPIN_UP = 'SPINNER_SPINUP';
export const SPIN_DOWN = 'SPINNER_SPINDOWN';
export const SPIN_RESET_WARNING = 'SPINNER_RESET_WARNING';
export const SPIN_RESET_ERROR = 'SPINNER_RESET_ERROR';
